# Model parameters in TOML format

title = "Degree day model parameter file for Halymorpha halys"
# This set up does NOT replace missing values with zeros

[runtime]
nNodes = 3           # Number of compute nodes to use
save2file = true     # If true save the results to a JLD2 file
save1year = true     # if true save first year's results, otherwise
                     # save all years from simYear tp simYear+meaxYears-1
missing2zero = false  # if true set anomaly missing values to zero (workaround for bug in the app)


[paths]   # All paths are relative to the user's home directory
output =  "OPRAM//results"      # Folder to save model output
results = "OPRAM//results"      # Folder for importing model results
data = "/Users/jon"                     # Folder for other model data
meteoIE = "/Users/jon/Google Drive/My Drive/Projects/DAFM_OPRAM/Data/Climate_JLD2"    # Folder containing meteo data for ROI
meteoNI =  "nothing"                     # Folder containing meteo data for NI

# These are the paths if running on the Linux office workstation
#output =  "/media/jon/Seagate_5TB/OPRAM_results"      # Folder to save model output
#results = "/media/jon/Seagate_5TB/OPRAM_results"     # Folder for importing model results
#data = "DATA//OPRAM"                     # Folder for other model data
#meteoIE = "DATA//OPRAM//Climate_JLD2"    # Folder containing meteo data for ROI
#meteoNI =  "nothing"                     # Folder containing meteo data for NI



[inputData]   # Input data on the model grid and species params
speciesFile = "git_repos/OPRAM/data/species_parameters.csv"
gridFile = "git_repos/OPRAM/data/IE_grid_locations.csv"
countyDefs = "git_repos/OPRAM/data/granite_county_defs.csv"



[model]     # Parameters to define the model
nReps = 1          # Number of replicates to run for future climates
futurePeriod = ["2021-2050", "2041-2070"]  # Climate future period
rcp = ["26","45","85"]                     # Climate future RCP
maxYears = 4         # Maximum number of years to complete insect development
country = "IE"       # Can be "IE", "NI" or "AllIreland"
thinFactor = 1       # Factor to thin grid (2 = sample every 2 km, 5 = sample every 5km)
method = "triangle"   # degree-day algorithm ("sine","triangle","average")
thirty_years = [1991, 2020]  # 30yr period to average
speciesList = ["Halyomorpha halys"]
